/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.bean.Cores;
import modelo.dao.CoresDAO;

/**
 *
 * @author Danilo
 */
public class CadCor extends javax.swing.JInternalFrame {

    int k;

    /**
     * Creates new form CadCores
     */
    public CadCor() {
        initComponents();

        bt_salvar.setVisible(false);
        bt_cancela.setVisible(false);
        bt_conCod.setVisible(false);
        bt_conDescri.setVisible(false);
        readTable();

    }

    public void readTable() {
        DefaultTableModel modelo = (DefaultTableModel) tb_cor.getModel();
        modelo.setNumRows(0);

        CoresDAO cdao = new CoresDAO();
        for (Cores c : cdao.findAll()) {
            modelo.addRow(new Object[]{
                c.getId(),
                c.getCod_cor(),
                c.getDes_cor(),});
        }
    }

    public void readTableForCod(String cod) {
        DefaultTableModel modelo = (DefaultTableModel) tb_cor.getModel();
        modelo.setNumRows(0);

        CoresDAO cdao = new CoresDAO();
        for (Cores c : cdao.readcod(cod)) {
            modelo.addRow(new Object[]{
                c.getId(),
                c.getCod_cor(),
                c.getDes_cor(),});
        }
    }
    
    public void readTableForDes(String cod) {
        DefaultTableModel modelo = (DefaultTableModel) tb_cor.getModel();
        modelo.setNumRows(0);

        CoresDAO cdao = new CoresDAO();
        for (Cores c : cdao.readdes(cod)) {
            modelo.addRow(new Object[]{
                c.getId(),
                c.getCod_cor(),
                c.getDes_cor(),});
        }
    }

    public void salvar() {
        Cores c = new Cores();
        CoresDAO dao = new CoresDAO();

        c.setCod_cor(txt_cod.getText());
        c.setDes_cor(txt_descricao.getText());
        c.setUs_cor(Principal.txt_stat_us.getText());

        dao.save(c);
        readTable();
    }

    public void edite() {
        Cores c = new Cores();
        CoresDAO dao = new CoresDAO();

        c.setCod_cor(txt_cod.getText());
        c.setDes_cor(txt_descricao.getText());
        c.setId((int) tb_cor.getValueAt(tb_cor.getSelectedRow(), 0));
        c.setUs_cor(Principal.txt_stat_us.getText());
        dao.updata(c);
        readTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_cod = new javax.swing.JTextField();
        txt_descricao = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        bt_novo = new javax.swing.JButton();
        bt_editar = new javax.swing.JButton();
        bt_Excluir = new javax.swing.JButton();
        bt_peq = new javax.swing.JButton();
        bt_cancela = new javax.swing.JButton();
        bt_salvar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_cor = new javax.swing.JTable();
        bt_conCod = new javax.swing.JButton();
        bt_conDescri = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setTitle("Cadastro de Cores");

        txt_cod.setEditable(false);

        txt_descricao.setEditable(false);

        jLabel1.setText("* Cod. Cor:");

        jLabel2.setText("* Descrição");

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        bt_novo.setText("Novo");
        bt_novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_novoActionPerformed(evt);
            }
        });

        bt_editar.setText("Edirar");
        bt_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_editarActionPerformed(evt);
            }
        });

        bt_Excluir.setText("Excluir");
        bt_Excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_ExcluirActionPerformed(evt);
            }
        });

        bt_peq.setText("Pesquisar");
        bt_peq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_peqActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bt_peq, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                    .addComponent(bt_novo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_editar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_Excluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bt_peq)
                .addGap(18, 18, 18)
                .addComponent(bt_novo)
                .addGap(18, 18, 18)
                .addComponent(bt_editar)
                .addGap(18, 18, 18)
                .addComponent(bt_Excluir)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        bt_cancela.setText("Cancelar");
        bt_cancela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_cancelaActionPerformed(evt);
            }
        });

        bt_salvar.setText("Salvar");
        bt_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_salvarActionPerformed(evt);
            }
        });

        jScrollPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane1MouseClicked(evt);
            }
        });

        tb_cor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Cod. Cor", "Descrição"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tb_cor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_corMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tb_corMouseEntered(evt);
            }
        });
        tb_cor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tb_corKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tb_corKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tb_cor);
        if (tb_cor.getColumnModel().getColumnCount() > 0) {
            tb_cor.getColumnModel().getColumn(0).setMinWidth(0);
            tb_cor.getColumnModel().getColumn(0).setPreferredWidth(1);
            tb_cor.getColumnModel().getColumn(0).setMaxWidth(0);
        }

        bt_conCod.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/search.png"))); // NOI18N
        bt_conCod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_conCodActionPerformed(evt);
            }
        });

        bt_conDescri.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/search.png"))); // NOI18N
        bt_conDescri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_conDescriActionPerformed(evt);
            }
        });

        jLabel8.setText("* campos obrigatorios");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel1)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txt_descricao, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txt_cod, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(bt_conCod, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(bt_conDescri, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(bt_cancela)
                                .addGap(23, 23, 23)
                                .addComponent(bt_salvar)
                                .addGap(35, 35, 35))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bt_conCod, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_cod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bt_conDescri, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_descricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bt_cancela)
                            .addComponent(bt_salvar))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_novoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_novoActionPerformed
        // TODO add your handling code here:

        txt_cod.setText("");
        txt_descricao.setText("");
        txt_cod.setEditable(true);
        txt_descricao.setEditable(true);
        bt_salvar.setVisible(true);
        bt_cancela.setVisible(true);
        bt_Excluir.setEnabled(false);
        bt_novo.setEnabled(false);
        bt_editar.setEnabled(false);
        tb_cor.setEnabled(false);
        tb_cor.clearSelection();
        bt_peq.setEnabled(false);
        bt_conCod.setVisible(false);
        bt_conDescri.setVisible(false);
        bt_conCod.setVisible(false);
        bt_conDescri.setVisible(false);
        readTable();

        k = 1;


    }//GEN-LAST:event_bt_novoActionPerformed

    private void tb_corKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tb_corKeyReleased
        // TODO add your handling code here:


    }//GEN-LAST:event_tb_corKeyReleased

    private void bt_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_editarActionPerformed
        // TODO add your handling code here:
        if (tb_cor.getSelectedRow() != -1) {

            txt_cod.setText((String) tb_cor.getValueAt(tb_cor.getSelectedRow(), 1));
            txt_descricao.setText((String) tb_cor.getValueAt(tb_cor.getSelectedRow(), 2));

            tb_cor.setEnabled(false);
            bt_salvar.setVisible(true);
            bt_cancela.setVisible(true);
            txt_cod.setEditable(true);
            txt_descricao.setEditable(true);
            bt_Excluir.setEnabled(false);
            bt_novo.setEnabled(false);
            bt_editar.setEnabled(false);
            bt_peq.setEnabled(false);
            bt_conCod.setVisible(false);
            bt_conDescri.setVisible(false);
            k = 2;

        } else {
            JOptionPane.showMessageDialog(null, "Selecione uma cor");
        }

    }//GEN-LAST:event_bt_editarActionPerformed

    private void bt_ExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_ExcluirActionPerformed
        // TODO add your handling code here:
        txt_cod.setText("");
        txt_descricao.setText("");
        if (tb_cor.getSelectedRow() != -1) {

            Cores c = new Cores();
            CoresDAO dao = new CoresDAO();

            int excluir = JOptionPane.showConfirmDialog(null, "Deseja excluir: " + (String) tb_cor.getValueAt(tb_cor.getSelectedRow(), 1));
            if (excluir == JOptionPane.YES_OPTION) {
                c.setId((int) tb_cor.getValueAt(tb_cor.getSelectedRow(), 0));
                dao.delete(c);
                readTable();
            }

        } else {
            JOptionPane.showMessageDialog(null, "Selecione uma cor");
        }
    }//GEN-LAST:event_bt_ExcluirActionPerformed

    private void bt_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_salvarActionPerformed
        // TODO add your handling code here:

        if (txt_cod.getText().equals("") | txt_descricao.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Prencha todos os campos!");
        } else {
            switch (k) {
                case 1:
                    salvar();
                    txt_cod.setText("");
                    txt_descricao.setText("");
                    txt_cod.setEditable(false);
                    txt_descricao.setEditable(false);
                    bt_salvar.setVisible(false);
                    bt_cancela.setVisible(false);
                    bt_Excluir.setEnabled(true);
                    bt_novo.setEnabled(true);
                    bt_editar.setEnabled(true);
                    tb_cor.setEnabled(true);
                    bt_peq.setEnabled(true);

                    break;
                case 2:
                    edite();
                    txt_cod.setText("");
                    txt_descricao.setText("");
                    txt_cod.setEditable(false);
                    txt_descricao.setEditable(false);
                    bt_salvar.setVisible(false);
                    bt_cancela.setVisible(false);
                    bt_Excluir.setEnabled(true);
                    bt_novo.setEnabled(true);
                    bt_editar.setEnabled(true);
                    tb_cor.setEnabled(true);
                    bt_peq.setEnabled(true);

                    break;
                default:
                    System.err.println("Erro:");
            }
        }

    }//GEN-LAST:event_bt_salvarActionPerformed

    private void bt_cancelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_cancelaActionPerformed
        // TODO add your handling code here:
        txt_cod.setText("");
        txt_descricao.setText("");
        txt_cod.setEditable(false);
        txt_descricao.setEditable(false);
        bt_salvar.setVisible(false);
        bt_cancela.setVisible(false);
        bt_Excluir.setEnabled(true);
        bt_novo.setEnabled(true);
        bt_editar.setEnabled(true);
        tb_cor.setEnabled(true);
        bt_peq.setEnabled(true);
        readTable();

    }//GEN-LAST:event_bt_cancelaActionPerformed

    private void tb_corMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_corMouseEntered
        // TODO add your handling code here:


    }//GEN-LAST:event_tb_corMouseEntered

    private void tb_corKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tb_corKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_tb_corKeyPressed

    private void tb_corMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_corMouseClicked
        // TODO add your handling code here:
        if (tb_cor.getSelectedRow() != -1) {
            txt_cod.setText((String) tb_cor.getValueAt(tb_cor.getSelectedRow(), 1));
            txt_descricao.setText((String) tb_cor.getValueAt(tb_cor.getSelectedRow(), 2));

        }
    }//GEN-LAST:event_tb_corMouseClicked

    private void bt_peqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_peqActionPerformed
        // TODO add your handling code here:
        txt_cod.setText("");
        txt_descricao.setText("");
        txt_cod.setEditable(true);
        tb_cor.clearSelection();
        tb_cor.setEnabled(false);
        bt_conCod.setVisible(true);
        bt_conDescri.setVisible(true);
        txt_descricao.setEditable(true);


    }//GEN-LAST:event_bt_peqActionPerformed

    private void bt_conCodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_conCodActionPerformed
        // TODO add your handling code here:

        readTableForCod(txt_cod.getText());
        tb_cor.setEnabled(true);
        txt_cod.setEditable(false);
        txt_descricao.setEditable(false);
        txt_cod.setText("");
        txt_descricao.setText("");
        bt_conCod.setVisible(false);
        bt_conDescri.setVisible(false);
    }//GEN-LAST:event_bt_conCodActionPerformed

    private void bt_conDescriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_conDescriActionPerformed
        // TODO add your handling code here:
        readTableForDes(txt_descricao.getText());
        tb_cor.setEnabled(true);
        txt_cod.setEditable(false);
        txt_descricao.setEditable(false);
        txt_cod.setText("");
        txt_descricao.setText("");
        bt_conCod.setVisible(false);
        bt_conDescri.setVisible(false);
    }//GEN-LAST:event_bt_conDescriActionPerformed

    private void jScrollPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_Excluir;
    private javax.swing.JButton bt_cancela;
    private javax.swing.JButton bt_conCod;
    private javax.swing.JButton bt_conDescri;
    private javax.swing.JButton bt_editar;
    private javax.swing.JButton bt_novo;
    private javax.swing.JButton bt_peq;
    private javax.swing.JButton bt_salvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tb_cor;
    private javax.swing.JTextField txt_cod;
    private javax.swing.JTextField txt_descricao;
    // End of variables declaration//GEN-END:variables
}
