/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.bean.Cliente;
import modelo.dao.ClienteDAO;

/**
 *
 * @author Danilo
 */
public class CadCliente extends javax.swing.JInternalFrame {

    /**
     * Creates new form CadCliente
     */
    public static String id;
    public static int k;

    public CadCliente() {
        initComponents();
        bt_conCnpj.setVisible(false);
        bt_conNome.setVisible(false);

        readTable();
    }

    public static void readTable() {
        DefaultTableModel modelo = (DefaultTableModel) JT_cliente.getModel();
        modelo.setNumRows(0);

        ClienteDAO dao = new ClienteDAO();
        for (Cliente c : dao.findAll()) {
            modelo.addRow(new Object[]{
                c.getId_cli(),
                c.getNome_cli(),
                c.getCnpj_cli(),});
        }
    }

    public void readNome(String cod) {
        DefaultTableModel modelo = (DefaultTableModel) JT_cliente.getModel();
        modelo.setNumRows(0);

        ClienteDAO dao = new ClienteDAO();
        for (Cliente c : dao.readNome(cod)) {
            modelo.addRow(new Object[]{
                c.getId_cli(),
                c.getNome_cli(),
                c.getCnpj_cli(),});
        }
    }

    public void readCnpj(String cod) {
        DefaultTableModel modelo = (DefaultTableModel) JT_cliente.getModel();
        modelo.setNumRows(0);

        ClienteDAO dao = new ClienteDAO();
        for (Cliente c : dao.readCnpj(cod)) {
            modelo.addRow(new Object[]{
                c.getId_cli(),
                c.getNome_cli(),
                c.getCnpj_cli(),});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtebel = new javax.swing.JScrollPane();
        JT_cliente = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        btn_novo = new javax.swing.JButton();
        btn_editar = new javax.swing.JButton();
        btn_excluir = new javax.swing.JButton();
        btn_sobre = new javax.swing.JButton();
        btn_pesq = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txt_cnpj = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_nome = new javax.swing.JTextField();
        bt_conCnpj = new javax.swing.JButton();
        bt_conNome = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Cadastro de Clientes");

        JT_cliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "TCNPJ"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        JT_cliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JT_clienteMouseClicked(evt);
            }
        });
        jtebel.setViewportView(JT_cliente);
        if (JT_cliente.getColumnModel().getColumnCount() > 0) {
            JT_cliente.getColumnModel().getColumn(0).setMinWidth(0);
            JT_cliente.getColumnModel().getColumn(0).setPreferredWidth(1);
            JT_cliente.getColumnModel().getColumn(0).setMaxWidth(0);
        }

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btn_novo.setText("Novo");
        btn_novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_novoActionPerformed(evt);
            }
        });

        btn_editar.setText("Editar");
        btn_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editarActionPerformed(evt);
            }
        });

        btn_excluir.setText("Excluir");
        btn_excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_excluirActionPerformed(evt);
            }
        });

        btn_sobre.setText("Sobre");
        btn_sobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sobreActionPerformed(evt);
            }
        });

        btn_pesq.setText("Pesquisar");
        btn_pesq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pesqActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_novo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_editar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_excluir, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                    .addComponent(btn_sobre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_pesq, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_pesq)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_novo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_editar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_excluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_sobre)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setText("CNPJ:");

        txt_cnpj.setEditable(false);
        try {
            txt_cnpj.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel2.setText("Nome Fantasia");

        txt_nome.setEditable(false);

        bt_conCnpj.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/search.png"))); // NOI18N
        bt_conCnpj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_conCnpjActionPerformed(evt);
            }
        });

        bt_conNome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/search.png"))); // NOI18N
        bt_conNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_conNomeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jtebel, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txt_cnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bt_conCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txt_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bt_conNome, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_cnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bt_conCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bt_conNome, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(jtebel, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_novoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_novoActionPerformed
        // TODO add your handling code here:
        k = 1;
        id = null;

        CadClienteAN cliente = new CadClienteAN();
        cliente.setVisible(true);
        Principal.Desktop.add(cliente);

        this.dispose();


    }//GEN-LAST:event_btn_novoActionPerformed

    private void btn_excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_excluirActionPerformed
        // TODO add your handling code here:
        if (JT_cliente.getSelectedRow() != -1) {
            Cliente c = new Cliente();
            ClienteDAO dao = new ClienteDAO();

            int excluir = JOptionPane.showConfirmDialog(null, "Deseja excluir: " + JT_cliente.getValueAt(JT_cliente.getSelectedRow(), 1));
            if (excluir == JOptionPane.YES_OPTION) {
                c.setId_cli((int) JT_cliente.getValueAt(JT_cliente.getSelectedRow(), 0));
                dao.delete(c);
                readTable();
                txt_nome.setText("");
                txt_cnpj.setText("");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Selecione um cliente");
        }
    }//GEN-LAST:event_btn_excluirActionPerformed

    private void JT_clienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JT_clienteMouseClicked
        // TODO add your handling code here:
        if (JT_cliente.getSelectedRow() != -1) {

            txt_nome.setText((String) JT_cliente.getValueAt(JT_cliente.getSelectedRow(), 1));
            txt_cnpj.setText((String) JT_cliente.getValueAt(JT_cliente.getSelectedRow(), 2));

        }
    }//GEN-LAST:event_JT_clienteMouseClicked

    private void btn_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editarActionPerformed
        // TODO add your handling code here:
        if (JT_cliente.getSelectedRow() != -1) {

            id = String.valueOf(JT_cliente.getValueAt(JT_cliente.getSelectedRow(), 0));
            k = 2;
            CadClienteAN cliente = new CadClienteAN();
            cliente.setVisible(true);
            Principal.Desktop.add(cliente);

            this.dispose();

        } else {
            JOptionPane.showMessageDialog(null, "Selecione um cliente");
        }
    }//GEN-LAST:event_btn_editarActionPerformed

    private void btn_pesqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pesqActionPerformed
        // TODO add your handling code here:
        txt_cnpj.setFormatterFactory(null);
        txt_cnpj.setText("");
        txt_nome.setText("");
        txt_nome.setEditable(true);
        txt_cnpj.setEditable(true);
        bt_conCnpj.setVisible(true);
        bt_conNome.setVisible(true);
        JT_cliente.setEnabled(false);


    }//GEN-LAST:event_btn_pesqActionPerformed

    private void btn_sobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sobreActionPerformed
        // TODO add your handling code here:
        if (JT_cliente.getSelectedRow() != -1) {

            id = String.valueOf(JT_cliente.getValueAt(JT_cliente.getSelectedRow(), 0));
            k = 3;

            CadClienteAN cliente = new CadClienteAN();
            cliente.setVisible(true);
            Principal.Desktop.add(cliente);
            this.dispose();

        } else {
            JOptionPane.showMessageDialog(null, "Selecione um cliente");
        }
    }//GEN-LAST:event_btn_sobreActionPerformed

    private void bt_conCnpjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_conCnpjActionPerformed
        // TODO add your handling code here:
        readCnpj(txt_cnpj.getText());

        txt_nome.setText("");
        txt_cnpj.setText("");
        txt_nome.setEditable(false);
        txt_cnpj.setEditable(false);
        bt_conCnpj.setVisible(false);
        bt_conNome.setVisible(false);
        JT_cliente.setEnabled(true);
    }//GEN-LAST:event_bt_conCnpjActionPerformed

    private void bt_conNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_conNomeActionPerformed
        // TODO add your handling code here:
        readNome(txt_nome.getText());
        txt_nome.setText("");
        txt_cnpj.setText("");
        txt_nome.setEditable(false);
        txt_cnpj.setEditable(false);
        bt_conCnpj.setVisible(false);
        bt_conNome.setVisible(false);
        JT_cliente.setEnabled(true);


    }//GEN-LAST:event_bt_conNomeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTable JT_cliente;
    private javax.swing.JButton bt_conCnpj;
    private javax.swing.JButton bt_conNome;
    private javax.swing.JButton btn_editar;
    private javax.swing.JButton btn_excluir;
    private javax.swing.JButton btn_novo;
    private javax.swing.JButton btn_pesq;
    private javax.swing.JButton btn_sobre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jtebel;
    private javax.swing.JFormattedTextField txt_cnpj;
    private javax.swing.JTextField txt_nome;
    // End of variables declaration//GEN-END:variables
}
