/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import model.bean.Cores;
import model.bean.Molde;
import model.bean.Produto;
import modelo.dao.MoldeDAO;
import modelo.dao.ProdutoDAO;
import modelo.dao.CoresDAO;
import static view.Principal.Desktop;

/**
 *
 * @author Danilo
 */
public class CadProdotoAN extends javax.swing.JInternalFrame {

    /**
     * Creates new form CadCliente
     */
    public void txtLiga() {

        txt_ref1.setEditable(true);
        txt_ref2.setEditable(true);
        txt_des.setEditable(true);
        txt_apli.setEditable(true);
        txt_apli.setEditable(true);
        txt_obs.setEditable(true);

        btn_salvar.setEnabled(true);
    }

    public void txtDesliga() {

    }

    public void preencher(String cod) {

        ProdutoDAO dao = new ProdutoDAO();
        for (Produto c : dao.readId(cod)) {

            txt_ref1.setText(c.getCodint_prod());
            txt_ref2.setText(c.getCodext_prod());
            txt_des.setText(c.getDes_prod());
            
            cbx_resina1.removeAllItems();
            cbx_resina1.addItem(c.getMp1_prod());
            cbx_resina2.addItem(c.getMp2_prod());
            
            txt_apli.setText(c.getApli_prod());
            if("".equals(c.getFab_prod())){
                
            }else{
                chb_fabri.isSelected();
            }
            if("".equals(c.getVal_prod())){
                
            }else{
                chb_validade.isSelected();
            }
            if("".equals(c.getAvi_prod())){
                chb_atoxico.isSelected();
            }
            txt_obs.setText(c.getObs_prod());
            preencherCombox();

        }
    }
    
    public void preencherCombox() {
            MoldeDAO mdao = new MoldeDAO();
            cbx_molde.removeAllItems();
            for (Molde p : mdao.findAll() ){
                cbx_molde.addItem(p);
            }
            CoresDAO cdao = new CoresDAO();
            cbx_cor.removeAllItems();
            for (Cores p : cdao.findAll() ){
                cbx_cor.addItem(p);
            }
    }

    public CadProdotoAN() {
        initComponents();
        switch (CadProduto.k) {
            case 1:
                txtLiga();
                preencherCombox();

                break;
            case 2:
                txtLiga();

                preencher(CadProduto.id);
                break;
            case 3:

                txtDesliga();

                preencher(CadProduto.id);
                break;
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jLabel8 = new javax.swing.JLabel();
        btn_cancelar = new javax.swing.JButton();
        btn_salvar = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cbx_resina1 = new javax.swing.JComboBox<>();
        cbx_resina2 = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        cbx_cor = new javax.swing.JComboBox<>();
        btn_cor = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txt_apli = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_ref1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_ref2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_des = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btn_mol = new javax.swing.JButton();
        cbx_molde = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_obs = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        chb_atoxico = new javax.swing.JCheckBox();
        chb_validade = new javax.swing.JCheckBox();
        chb_fabri = new javax.swing.JCheckBox();

        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        setTitle("Cadastro de Molde");

        jLabel8.setText("* campos obrigatorios");

        btn_cancelar.setText("Cancelar");
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });

        btn_salvar.setText("Salvar");
        btn_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salvarActionPerformed(evt);
            }
        });

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Materia Prima"));

        jLabel4.setText("Resina:");

        jLabel5.setText("Resina:");

        cbx_resina1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ND", "PP1", "PP2", "RP", "IF", "PP baixa" }));

        cbx_resina2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ND", "PP1", "PP2", "RP", "IF", "PP baixa" }));

        jLabel7.setText("Pigmentação:");

        cbx_cor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_corActionPerformed(evt);
            }
        });

        jLabel9.setText("Aplicação (%):");

        txt_apli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_apliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbx_resina1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(cbx_resina2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(cbx_cor, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_cor, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel7))
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(txt_apli, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jLabel9)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbx_resina1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbx_resina2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_cor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbx_cor)
                    .addComponent(txt_apli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Produto"));

        jLabel1.setText("* Cod Plastow:");

        jLabel3.setText("Cod Cliente:");

        jLabel2.setText("* Descrição:");

        jLabel6.setText("* Molde");

        cbx_molde.setEditable(true);
        cbx_molde.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cbx_moldeFocusGained(evt);
            }
        });
        cbx_molde.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbx_moldeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cbx_moldeMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cbx_moldeMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                cbx_moldeMouseReleased(evt);
            }
        });
        cbx_molde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_moldeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_des)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cbx_molde, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_mol, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(txt_ref1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(txt_ref2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_ref1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_ref2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_des, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_mol, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(cbx_molde, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Observação"));

        txt_obs.setColumns(20);
        txt_obs.setRows(5);
        txt_obs.setText("CUIDADO NO MANUSEIO, TRANSPORTE E ARMAZENAMENTO DO PRODUTO.\nPROTEGER DE INTEMPÉRIE.\nSUGEITO A PERDA DA GARANTIA.");
        jScrollPane1.setViewportView(txt_obs);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Outros"));

        chb_atoxico.setText("Material atóxico para fins cosmeticos.");

        chb_validade.setText("Data de Validade padrão");

        chb_fabri.setText("Data de Fabricação padrão");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(chb_fabri)
                        .addGap(10, 10, 10)
                        .addComponent(chb_validade))
                    .addComponent(chb_atoxico))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chb_fabri)
                    .addComponent(chb_validade))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chb_atoxico))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(149, 149, 149)
                            .addComponent(btn_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btn_salvar, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_salvar)
                    .addComponent(btn_cancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salvarActionPerformed
        // TODO add your handling code here:
        try {
            if ("".equals(txt_ref1.getText()) | "".equals(txt_des.getText()) | "".equals(cbx_molde.getSelectedItem()) ) {
                JOptionPane.showMessageDialog(null, "Digite todos os campos obrigatorios!");

            } else {
                if (CadProduto.id == null) {
                    ProdutoDAO dao = new ProdutoDAO();
                    Produto c = new Produto();
                    Cores pc = (Cores) cbx_cor.getSelectedItem();
                    Molde pm = (Molde) cbx_molde.getSelectedItem();

                    c.setCodint_prod(txt_ref1.getText());
                    c.setCodext_prod(txt_ref2.getText());
                    c.setDes_prod(txt_des.getText());
                    c.setMp1_prod((String) cbx_resina1.getSelectedItem());
                    c.setMp2_prod((String) cbx_resina2.getSelectedItem());
                    c.setCor_prod(pc.getCod_cor());
                    c.setApli_prod(txt_apli.getText());
                    c.setMol_prod(pm.getDes_mol());
                    String avi, fab, val;
                    if (chb_atoxico.isSelected()) {
                        avi = "Material atóxico para fins cosmeticos.";
                    } else {
                        avi = "";
                    }
                    c.setAvi_prod(avi);
                    if (chb_fabri.isSelected()) {
                        fab = "IMPRESSO NA ETIQUETA";
                    } else {
                        fab = "";
                    }
                    c.setFab_prod(fab);
                    if (chb_validade.isSelected()) {
                        val = "VINTE E QUATRO MESES";
                    } else {
                        val = "";
                    }
                    c.setVal_prod(val);
                    c.setObs_prod(txt_obs.getText());
                    c.setUs_prod(Principal.txt_stat_us.getText());

                    dao.save(c);

                    CadProduto.id = null;

                    CadProduto tela = new CadProduto();
                    tela.setVisible(true);
                    Desktop.add(tela);
                    this.dispose();

                } else {
                    ProdutoDAO dao = new ProdutoDAO();
                    Produto c = new Produto();
                    Cores pc = (Cores) cbx_cor.getSelectedItem();
                    Molde pm = (Molde) cbx_molde.getSelectedItem();

                    c.setCodint_prod(txt_ref1.getText());
                    c.setCodext_prod(txt_ref2.getText());
                    c.setDes_prod(txt_des.getText());
                    c.setMp1_prod((String) cbx_resina1.getSelectedItem());
                    c.setMp2_prod((String) cbx_resina2.getSelectedItem());
                    c.setCor_prod(pc.getCod_cor());
                    c.setApli_prod(txt_apli.getText());
                    c.setMol_prod(pm.getDes_mol());
                    String avi, fab, val;
                    if (chb_atoxico.isSelected()) {
                        avi = "Material atóxico para fins cosmeticos.";
                    } else {
                        avi = "";
                    }
                    c.setAvi_prod(avi);
                    if (chb_fabri.isSelected()) {
                        fab = "IMPRESSO NA ETIQUETA";
                    } else {
                        fab = "";
                    }
                    c.setFab_prod(fab);
                    if (chb_validade.isSelected()) {
                        val = "VINTE E QUATRO MESES";
                    } else {
                        val = "";
                    }
                    c.setVal_prod(val);
                    c.setObs_prod(txt_obs.getText());
                    c.setUs_prod(Principal.txt_stat_us.getText());
                    c.setId_prod(Integer.valueOf(CadProduto.id));
                    dao.updata(c);

                    CadMolde.id = null;

                    CadProduto tela = new CadProduto();
                    tela.setVisible(true);
                    Desktop.add(tela);
                    this.dispose();
                }
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Insira um Valor valido em peso!");
        }
    }//GEN-LAST:event_btn_salvarActionPerformed

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
        // TODO add your handling code here:

        CadMolde tela = new CadMolde();
        tela.setVisible(true);
        Desktop.add(tela);
        this.dispose();

    }//GEN-LAST:event_btn_cancelarActionPerformed

    private void cbx_corActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_corActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbx_corActionPerformed

    private void txt_apliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_apliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_apliActionPerformed

    private void cbx_moldeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cbx_moldeFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_cbx_moldeFocusGained

    private void cbx_moldeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbx_moldeMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_cbx_moldeMouseClicked

    private void cbx_moldeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbx_moldeMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_cbx_moldeMouseEntered

    private void cbx_moldeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbx_moldeMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbx_moldeMousePressed

    private void cbx_moldeMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbx_moldeMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_cbx_moldeMouseReleased

    private void cbx_moldeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_moldeActionPerformed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_cbx_moldeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JButton btn_cor;
    private javax.swing.JButton btn_mol;
    private javax.swing.JButton btn_salvar;
    private javax.swing.JComboBox<Object> cbx_cor;
    private javax.swing.JComboBox<Object> cbx_molde;
    private javax.swing.JComboBox<Object> cbx_resina1;
    private javax.swing.JComboBox<Object> cbx_resina2;
    private javax.swing.JCheckBox chb_atoxico;
    private javax.swing.JCheckBox chb_fabri;
    private javax.swing.JCheckBox chb_validade;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txt_apli;
    private javax.swing.JTextField txt_des;
    private javax.swing.JTextArea txt_obs;
    private javax.swing.JTextField txt_ref1;
    private javax.swing.JTextField txt_ref2;
    // End of variables declaration//GEN-END:variables

}
