/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.bean.Molde;
import model.bean.Produto;
import modelo.dao.MoldeDAO;
import modelo.dao.ProdutoDAO;
import static view.CadMolde.JT_lista;

/**
 *
 * @author Danilo
 */
public class CadProduto extends javax.swing.JInternalFrame {

    /**
     * Creates new form CadCliente
     */
    public static String id;
    public static int k;

    public CadProduto() {
        initComponents();
        bt_con1.setVisible(false);
        bt_con2.setVisible(false);

        readTable();
    }

    public static void readTable() {
        DefaultTableModel modelo = (DefaultTableModel) JT_lista.getModel();
        modelo.setNumRows(0);

        ProdutoDAO dao = new ProdutoDAO();
                
        for (Produto c: dao.findAll()) {
                     
            modelo.addRow(new Object[]{ c.getId_prod(),
                c.getCodint_prod(), 
                c.getDes_prod(), 
                c.getMol_prod(),});
        }
    }

    public void readId(String cod) {
        DefaultTableModel modelo1 = (DefaultTableModel) JT_lista.getModel();
        modelo1.setNumRows(0);

        MoldeDAO dao = new MoldeDAO();
        for (Molde c : dao.readId(cod)) {
            modelo1.addRow(new Object[]{
            c.getDes_mol(),});
        }
    }

    public void readRef(String cod) {
        DefaultTableModel modelo = (DefaultTableModel) JT_lista.getModel();
        modelo.setNumRows(0);

        ProdutoDAO dao = new ProdutoDAO();
        for (Produto c : dao.readCod(cod)) {
            modelo.addRow(new Object[]{
                c.getId_prod(),
                c.getCodint_prod(),
                c.getMol_prod(),});
        }
    }

    public void readDes(String cod) {
        DefaultTableModel modelo = (DefaultTableModel) JT_lista.getModel();
        modelo.setNumRows(0);

        ProdutoDAO dao = new ProdutoDAO();
        for (Produto c : dao.readDes(cod)) {
            modelo.addRow(new Object[]{
                c.getId_prod(),
                c.getCodint_prod(),
                c.getMol_prod(),});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtebel = new javax.swing.JScrollPane();
        JT_lista = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        btn_novo = new javax.swing.JButton();
        btn_editar = new javax.swing.JButton();
        btn_excluir = new javax.swing.JButton();
        btn_sobre = new javax.swing.JButton();
        btn_pesq = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_nome = new javax.swing.JTextField();
        bt_con1 = new javax.swing.JButton();
        bt_con2 = new javax.swing.JButton();
        txt_cod = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setTitle("Cadastro de Molde");

        JT_lista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Cod. Plastow", "Descrição", "Molde"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        JT_lista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JT_listaMouseClicked(evt);
            }
        });
        jtebel.setViewportView(JT_lista);
        if (JT_lista.getColumnModel().getColumnCount() > 0) {
            JT_lista.getColumnModel().getColumn(0).setMinWidth(0);
            JT_lista.getColumnModel().getColumn(0).setPreferredWidth(1);
            JT_lista.getColumnModel().getColumn(0).setMaxWidth(0);
        }

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btn_novo.setText("Novo");
        btn_novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_novoActionPerformed(evt);
            }
        });

        btn_editar.setText("Editar");
        btn_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editarActionPerformed(evt);
            }
        });

        btn_excluir.setText("Excluir");
        btn_excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_excluirActionPerformed(evt);
            }
        });

        btn_sobre.setText("Sobre");
        btn_sobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sobreActionPerformed(evt);
            }
        });

        btn_pesq.setText("Pesquisar");
        btn_pesq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pesqActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_novo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_editar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_excluir, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                    .addComponent(btn_sobre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_pesq, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_pesq)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_novo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_editar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_excluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_sobre)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setText("Cod. Plastow:");

        jLabel2.setText("Descrição:");

        txt_nome.setEditable(false);

        bt_con1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/search.png"))); // NOI18N
        bt_con1.setToolTipText("");
        bt_con1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_con1ActionPerformed(evt);
            }
        });

        bt_con2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/search.png"))); // NOI18N
        bt_con2.setToolTipText("");
        bt_con2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_con2ActionPerformed(evt);
            }
        });

        txt_cod.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jtebel, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txt_cod, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bt_con1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txt_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bt_con2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bt_con1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_cod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bt_con2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(jtebel, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_novoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_novoActionPerformed
        // TODO add your handling code here:
        k = 1;
        id = null;

        CadProdotoAN tela = new CadProdotoAN();
        tela.setVisible(true);
        Principal.Desktop.add(tela);

        this.dispose();


    }//GEN-LAST:event_btn_novoActionPerformed

    private void btn_excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_excluirActionPerformed
        // TODO add your handling code here:
        if (JT_lista.getSelectedRow() != -1) {
            Produto c = new Produto();
            ProdutoDAO dao = new ProdutoDAO();

            int excluir = JOptionPane.showConfirmDialog(null, "Deseja excluir: " + JT_lista.getValueAt(JT_lista.getSelectedRow(), 1));
            if (excluir == JOptionPane.YES_OPTION) {
                c.setId_prod((int) JT_lista.getValueAt(JT_lista.getSelectedRow(), 0));
                dao.delete(c);
                readTable();
                
            }
        } else {
            JOptionPane.showMessageDialog(null, "Selecione um molde");
        }
    }//GEN-LAST:event_btn_excluirActionPerformed

    private void JT_listaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JT_listaMouseClicked
        // TODO add your handling code here:
        if (JT_lista.getSelectedRow() != -1) {

            txt_cod.setText((String) JT_lista.getValueAt(JT_lista.getSelectedRow(), 1));
            txt_nome.setText((String) JT_lista.getValueAt(JT_lista.getSelectedRow(), 2));

        }
    }//GEN-LAST:event_JT_listaMouseClicked

    private void btn_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editarActionPerformed
        // TODO add your handling code here:
        if (JT_lista.getSelectedRow() != -1) {

            id = String.valueOf(JT_lista.getValueAt(JT_lista.getSelectedRow(), 0));
            k = 2;
            CadProdotoAN tela = new CadProdotoAN();
            tela.setVisible(true);
            Principal.Desktop.add(tela);

            this.dispose();

        } else {
            JOptionPane.showMessageDialog(null, "Selecione um molde");
        }
    }//GEN-LAST:event_btn_editarActionPerformed

    private void btn_pesqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pesqActionPerformed
        // TODO add your handling code here:
        txt_cod.setText("");
        txt_nome.setText("");
        txt_nome.setEditable(true);
        txt_cod.setEditable(true);
        bt_con1.setVisible(true);
        bt_con2.setVisible(true);
        JT_lista.setEnabled(false);


    }//GEN-LAST:event_btn_pesqActionPerformed

    private void btn_sobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sobreActionPerformed
        // TODO add your handling code here:
        if (JT_lista.getSelectedRow() != -1) {

            id = String.valueOf(JT_lista.getValueAt(JT_lista.getSelectedRow(), 0));
            k = 3;

            CadProdotoAN tela = new CadProdotoAN();
            tela.setVisible(true);
            Principal.Desktop.add(tela);
            //tela.requestFocus(true);
            //try {
            //    tela.setSelected(true);
            //} catch (PropertyVetoException ex) {
            //}
            this.dispose();

        } else {
            JOptionPane.showMessageDialog(null, "Selecione um molde");
        }
    }//GEN-LAST:event_btn_sobreActionPerformed

    private void bt_con1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_con1ActionPerformed
        // TODO add your handling code here:
        readRef(txt_cod.getText());

        txt_nome.setText("");
        txt_cod.setText("");
        txt_nome.setEditable(false);
        txt_cod.setEditable(false);
        bt_con1.setVisible(false);
        bt_con2.setVisible(false);
        JT_lista.setEnabled(true);
    }//GEN-LAST:event_bt_con1ActionPerformed

    private void bt_con2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_con2ActionPerformed
        // TODO add your handling code here:
        readDes(txt_nome.getText());
        txt_nome.setText("");
        txt_cod.setText("");
        txt_nome.setEditable(false);
        txt_cod.setEditable(false);
        bt_con1.setVisible(false);
        bt_con2.setVisible(false);
        JT_lista.setEnabled(true);


    }//GEN-LAST:event_bt_con2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTable JT_lista;
    private javax.swing.JButton bt_con1;
    private javax.swing.JButton bt_con2;
    private javax.swing.JButton btn_editar;
    private javax.swing.JButton btn_excluir;
    private javax.swing.JButton btn_novo;
    private javax.swing.JButton btn_pesq;
    private javax.swing.JButton btn_sobre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jtebel;
    private javax.swing.JTextField txt_cod;
    private javax.swing.JTextField txt_nome;
    // End of variables declaration//GEN-END:variables
}
