/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.PopupMenu;
import javax.swing.JOptionPane;
import model.bean.Usuario;
import modelo.dao.UsuarioDAO;

/**
 *
 * @author Danilo
 */
public class CadUsuario extends javax.swing.JInternalFrame {

    int k;

    /**
     * Creates new form CadUsuario1
     */
    public void caregatela() {

        txt_senha.setVisible(false);
        txt_confSenha.setVisible(false);
        txt_login.setEditable(false);

        lb_senha.setVisible(false);
        lb_cofSenha.setVisible(false);

        btn_salvar.setVisible(false);
        btn_cancelar.setVisible(false);
        btn_excluir.setEnabled(true);
        btn_alterar.setEnabled(true);
        btn_novo.setEnabled(true);

        btr_adimin.setEnabled(false);
        btr_user.setEnabled(false);

        cb_usuario.setEnabled(true);
        cb_usuario.setEditable(false);
        cb_usuario.removeAllItems();

        UsuarioDAO dao = new UsuarioDAO();

        for (Usuario u : dao.findAll()) {

            cb_usuario.addItem(u);

        }

    }

    public void alterar() {
        cb_usuario.setEnabled(false);

        txt_senha.setVisible(true);
        txt_confSenha.setVisible(true);
        txt_login.setEditable(true);

        lb_senha.setVisible(true);
        lb_cofSenha.setVisible(true);

        btn_salvar.setVisible(true);
        btn_cancelar.setVisible(true);

        btr_adimin.setEnabled(true);
        btr_user.setEnabled(true);

        btn_excluir.setEnabled(false);
        btn_alterar.setEnabled(false);
        btn_novo.setEnabled(false);
    }

    public void novo() {
        String us = txt_login.getText();
        String senha = String.valueOf(txt_senha.getPassword());
        String conSenha = String.valueOf(txt_confSenha.getPassword());
        String nome = (String) cb_usuario.getSelectedItem();
        String per = null;

        if (btr_adimin.isSelected()) {
            per = "admin";
        } else {
            per = "user";
        }

        Usuario use = new Usuario(nome, us, senha, per);
        UsuarioDAO dao = new UsuarioDAO();

        if ("".equals(nome) | "".equals(us) | "".equals(senha)) {
            JOptionPane.showMessageDialog(null, "Preencha todos os campos!");
        } else {

            if ("".equals(per)) {
                JOptionPane.showMessageDialog(null, "Selecione uma permição!");
            } else {

                if (senha.equals(conSenha)) {

                    if (dao.save(use)) {
                        JOptionPane.showMessageDialog(null, "Usuario salvo com sucesso!");
                        caregatela();
                    } else {
                        JOptionPane.showMessageDialog(null, "Erro ao salvar!");
                    }

                } else {
                    JOptionPane.showMessageDialog(null, "As senhas não coferem!");
                }
            }
        }
    }

    public void atualizar() {
        String per;

        if (btr_adimin.isSelected()) {
            per = "admin";
        } else {
            per = "user";
        }

        UsuarioDAO dao = new UsuarioDAO();
        Usuario us = (Usuario) cb_usuario.getSelectedItem();
        us.setNome_log(us.getNome_log());
        us.setUsuario_log(txt_login.getText());
        us.setSenha_log(String.valueOf(txt_senha.getPassword()));
        us.setPermica_log(per);
        us.setId_us(us.getId_us());

        if ("".equals(txt_login.getText()) | "".equals(String.valueOf(txt_senha.getPassword()))) {
            JOptionPane.showMessageDialog(null, "Preencha todos os campos!");
        } else {

            if ("".equals(per)) {
                JOptionPane.showMessageDialog(null, "Selecione uma permição!");
            } else {

                if (String.valueOf(txt_senha.getPassword()).equals(String.valueOf(txt_confSenha.getPassword()))) {

                    if (dao.updata(us)) {
                        JOptionPane.showMessageDialog(null, "Usuario alterado com sucesso!");
                        caregatela();
                    } else {
                        JOptionPane.showMessageDialog(null, "Erro ao alterar!");
                    }

                } else {
                    JOptionPane.showMessageDialog(null, "As senhas não coferem!");
                }
            }
        }

    }

    public CadUsuario() {
        initComponents();

        caregatela();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lb_senha = new javax.swing.JLabel();
        lb_cofSenha = new javax.swing.JLabel();
        txt_login = new javax.swing.JTextField();
        txt_senha = new javax.swing.JPasswordField();
        txt_confSenha = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        cb_usuario = new javax.swing.JComboBox<>();
        btr_adimin = new javax.swing.JRadioButton();
        btr_user = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        btn_novo = new javax.swing.JButton();
        btn_alterar = new javax.swing.JButton();
        btn_excluir = new javax.swing.JButton();
        btn_salvar = new javax.swing.JButton();
        btn_cancelar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Cadastro de Usuarios");

        jLabel1.setText("Nome:");

        jLabel2.setText("Login:");

        lb_senha.setText("Senha:");

        lb_cofSenha.setText("Confirma senha:");

        txt_login.setEditable(false);

        jLabel5.setText("Permiçoes:");

        cb_usuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cb_usuarioFocusGained(evt);
            }
        });
        cb_usuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cb_usuarioMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cb_usuarioMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cb_usuarioMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                cb_usuarioMouseReleased(evt);
            }
        });
        cb_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_usuarioActionPerformed(evt);
            }
        });

        buttonGroup1.add(btr_adimin);
        btr_adimin.setText("Adiministrador");
        btr_adimin.setEnabled(false);

        buttonGroup1.add(btr_user);
        btr_user.setText("Usuario");
        btr_user.setEnabled(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btn_novo.setText("Novo");
        btn_novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_novoActionPerformed(evt);
            }
        });

        btn_alterar.setText("Alterar");
        btn_alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_alterarActionPerformed(evt);
            }
        });

        btn_excluir.setText("Excluir");
        btn_excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_excluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_novo, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_alterar, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_excluir, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_novo)
                .addGap(18, 18, 18)
                .addComponent(btn_alterar)
                .addGap(18, 18, 18)
                .addComponent(btn_excluir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btn_salvar.setText("Salvar");
        btn_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salvarActionPerformed(evt);
            }
        });

        btn_cancelar.setText("Cancela");
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(lb_senha)))
                    .addComponent(lb_cofSenha, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_login, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cb_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(btr_adimin)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btr_user)
                                    .addGap(11, 11, 11))
                                .addComponent(txt_senha, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_salvar, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txt_confSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cb_usuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(btr_adimin)
                    .addComponent(btr_user))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_senha)
                    .addComponent(txt_senha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_cofSenha)
                    .addComponent(txt_confSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_salvar)
                    .addComponent(btn_cancelar))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        setBounds(0, 0, 417, 273);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salvarActionPerformed
        switch (k) {
            case 1:
                novo();
                break;
            case 2:
                atualizar();
                break;
            default:
                System.err.println("Erro:");
        }
    }//GEN-LAST:event_btn_salvarActionPerformed

    private void cb_usuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cb_usuarioMouseClicked
        // TODO add your handling code here:


    }//GEN-LAST:event_cb_usuarioMouseClicked

    private void cb_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_usuarioActionPerformed
        // TODO add your handling code here:
        try {
            Usuario us = (Usuario) cb_usuario.getSelectedItem();
            txt_login.setText(us.getUsuario_log());
            txt_senha.setText(us.getSenha_log());
            txt_confSenha.setText("");

            if (us.getPermica_log().equals("admin")) {
                btr_adimin.setSelected(true);
            } else {
                btr_user.setSelected(true);
            }
        } catch (Exception e) {
            txt_login.setText("");
            txt_senha.setText("");
        }

    }//GEN-LAST:event_cb_usuarioActionPerformed

    private void btn_alterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_alterarActionPerformed
        // TODO add your handling code here:
        alterar();
        k = 2;

    }//GEN-LAST:event_btn_alterarActionPerformed

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
        // TODO add your handling code here:
        caregatela();


    }//GEN-LAST:event_btn_cancelarActionPerformed

    private void btn_novoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_novoActionPerformed
        // TODO add your handling code here:
        cb_usuario.removeAllItems();
        cb_usuario.setEditable(true);

        lb_senha.setVisible(true);
        lb_cofSenha.setVisible(true);

        txt_login.setEditable(true);
        txt_senha.setVisible(true);
        txt_confSenha.setVisible(true);

        btr_adimin.setEnabled(true);
        btr_user.setEnabled(true);

        btn_novo.setEnabled(false);
        btn_excluir.setEnabled(false);
        btn_alterar.setEnabled(false);

        btn_cancelar.setVisible(true);
        btn_salvar.setVisible(true);

        k = 1;


    }//GEN-LAST:event_btn_novoActionPerformed

    private void cb_usuarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cb_usuarioMouseEntered
        // TODO add your handling code here:

    }//GEN-LAST:event_cb_usuarioMouseEntered

    private void cb_usuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cb_usuarioMousePressed
        // TODO add your handling code here:

    }//GEN-LAST:event_cb_usuarioMousePressed

    private void cb_usuarioMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cb_usuarioMouseReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_cb_usuarioMouseReleased

    private void cb_usuarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cb_usuarioFocusGained
        // TODO add your handling code here:

    }//GEN-LAST:event_cb_usuarioFocusGained

    private void btn_excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_excluirActionPerformed
        // TODO add your handling code here:
        UsuarioDAO dao = new UsuarioDAO();
        Usuario us = (Usuario) cb_usuario.getSelectedItem();

        int excluir = JOptionPane.showConfirmDialog(null, "Deseja excluir: " + us.getNome_log());
        if (excluir == JOptionPane.YES_OPTION) {
            us.setId_us(us.getId_us());

            dao.delete(us);
            caregatela();
        }
        caregatela();


    }//GEN-LAST:event_btn_excluirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_alterar;
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JButton btn_excluir;
    private javax.swing.JButton btn_novo;
    private javax.swing.JButton btn_salvar;
    private javax.swing.JRadioButton btr_adimin;
    private javax.swing.JRadioButton btr_user;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<Object> cb_usuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lb_cofSenha;
    private javax.swing.JLabel lb_senha;
    private javax.swing.JPasswordField txt_confSenha;
    private javax.swing.JTextField txt_login;
    private javax.swing.JPasswordField txt_senha;
    // End of variables declaration//GEN-END:variables

    private PopupMenu pl(String permica_log) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
